### ISSUE TITLE
Badge/Registration Reports Required

### ISSUE THREAD

**Issue by AricStewart** [CON-In-A-Box/CIAB-Portal#231]
1.  List of all memberships sold
1.  Summary of all memberships sold
1.  All Transactions
1.  Declined/failed transactions
1.  Summary of picked up memberships
1.  List of all badge names W/ numbers and type
1.  Revenue summary (by membership type, date, and/or ConYear)

**Comment by AricStewart** [comment]
[WOW a test Event-Con_ All Registrations.txt](https://github.com/CON-In-A-Box/CIAB-Portal/files/3903290/WOW.a.test.Event-Con_.All.Registrations.txt)
[WOW a test Event-Con_ Badges Picked Up.txt](https://github.com/CON-In-A-Box/CIAB-Portal/files/3903291/WOW.a.test.Event-Con_.Badges.Picked.Up.txt)

I think those reports cover points 1, 2, 5, and 6.

Could someone better descibe 7?

We do not have the data for 3 and 4 until we start doing CC processing. 

If you want more refined reports then I need them more well defined.

**Comment by dleverentz** [comment]
First thing - could you put together a glossary of what the column names mean? @AricStewart

**Comment by dleverentz** [comment]
Also, it is much easier for user if these are available in CSV format vs txt.

**Comment by AricStewart** [comment]
When you are done breaking it all out could you then close this issue please.
Thanks!

**Comment by dleverentz** [comment]
Who provided the information for this list? I want to ensure I'm covering everything before I close this out. @AricStewart
