### ISSUE TITLE
Users are unable to authenticate due to duplicate accounts being created

### ISSUE THREAD

**Issue by seanbseanb** [CON-In-A-Box/CIAB-Portal#239]
We see several incidents per month when duplicate accounts are created in CIAB.  How do we intelligently prevent duplicate accounts from being created?

Related: how do we automate the merging of duplicate accounts in CIAB (or prevent duplicate account creation), similar to the manual process Registration does in NeonCRM today?

**Comment by AricStewart** [comment]
Did this occur very recently?

Thomas! Has the most recent code been merged into production?

As of the most recent code (Jan 22nd) people with duplicate accounts should still be able to log in with their primary account and get a warning. 

I am working out the logic for a merge process but right now it would have to be done by hand.

**Comment by tskeeley** [comment]
The push to production had not happened at the time of this report.

This issue should continue to relate to the merge work (if/when we get there)

**Comment by AricStewart** [comment]
Appears to be fixed. will reopen if problem occurs.
