### ISSUE TITLE
Registration: Guest lookup should have a search button 

### ISSUE THREAD

**Issue by seanbseanb** [CON-In-A-Box/CIAB-Portal#259]
In the current UI, immediately right of the search box is a “barcode” icon.  Instead of this, I would expect a rounded button saying something like “search” or “lookup”, spaced in the usual amount from the search box.

**Comment by AricStewart** [comment]
You want a partial text lookup? I have that implement but mostly turned off.
Enter key or clicking anywhere outside of the box  is the trigger to go. 
Do we need to have an arrow or something to click on?

**Comment by mshappe** [comment]
I believe the request is specifically a UI comment: the image on the "search" button should be an obvious search icon -- these days, usually a magnifying glass icon -- or else the word "search", not a barcode.

**Comment by mshappe** [comment]
Oh, wait, I see -- the barcode is not the search button anyway -- it's the "turn on the camera so I can scan a barcode" button.

That's great, but there should also be a search button that does the same thing as hitting enter or tabbing out of the entry blank.

**Comment by mshappe** [comment]
Also, the barcode icon should have hover-text that makes it clear that it's a "scan barcode" button.
