### ISSUE TITLE
Login: Login isn’t always successful, and no error message is shown to the user

### ISSUE THREAD

**Issue by seanbseanb** [CON-In-A-Box/CIAB-Portal#260]
We sometimes see an error in the Apache logs that looks like this: [Thu Apr 11 21:53:11.589242 2019] [:error] [pid 4753] [client 96.75.144.29:53005
] PHP Notice:  Undefined index: FirstName in REDACTED/public_html/CIAB-Signin/
functions/authentication.inc on line 242, referer: https://REDACTED/ind
ex.php?Function=public

**Comment by AricStewart** [comment]
I strongly believe I have fixed this.
