### ISSUE TITLE
Forgot password return

### ISSUE THREAD

**Issue by dleverentz** [CON-In-A-Box/CIAB-Portal#282]
As a user, when I request a password reset, I can return to the sign-in screen so I can complete the reset process. 

Acceptance Criteria

- [ ] User selects a single place to initiate return
- [ ] User is returned to the sign in screen

**Comment by AricStewart** [comment]
This should be in place. Please test and confirm.

**Comment by AricStewart** [comment]
Closed. Reopen if further issues exist
