### ISSUE TITLE
Portal: Department Management: "removing" a member should just flag their assignment as "ended"

### ISSUE THREAD

**Issue by mshappe** [CON-In-A-Box/CIAB-Portal#302]
So that we can keep track of historic department membership, rather than actually deleting a membership record when someone is removed from a department, their membership should be flagged with an `EndedOn` datestamp. The main concom list could then just display those for whom `EndedOn IS NULL` and we can build out a way of looking at historic membership later.

**Comment by AricStewart** [comment]
I believe this is in and working. Please test.
