### ISSUE TITLE
Portal: Deleting departments currently does not work at all

### ISSUE THREAD

**Issue by mshappe** [CON-In-A-Box/CIAB-Portal#304]
Even if the staff count is 0, the button to delete a department is greyed out.

**Comment by AricStewart** [comment]
Test and confirm please

**Comment by mshappe** [comment]
Deleting Future Visioning (which correctly shows 0 members now) returns a
500 in the console.

**Comment by AricStewart** [comment]
Correction made.  Please tryin again.

**Comment by mshappe** [comment]
This now works. However, ADDING a department, adding an e-mail 500s.

**Comment by mshappe** [comment]
Correction: if I actually remember to SAVE the new department, then adding
email to it works. Adding email should either work before it's saved, or
not be available before it's saved, just to prevent the mistake.

**Comment by AricStewart** [comment]
Is this fixed?

**Comment by mshappe** [comment]
Yes
