### ISSUE TITLE
Portal: Concom List: A person's mambership should be editable, not just remove/add-again

### ISSUE THREAD

**Issue by mshappe** [CON-In-A-Box/CIAB-Portal#307]
It should be possible to edit (and hence correct) a person's entry on the concom list. For example, I should be able to select Lauren under Member Advocates and add/change a note to refer to the fact that she's actually a Board Liaison.

(Interestingly, removing her and re-adding her, with the note, didn't work -- she showed up without the note, still)

**Comment by AricStewart** [comment]
Fixed the note part but I want to know some of the work flow here.

- Changing Notes:  Easy
- Changing Positions in a department.  Can only be done by department head (positions < head) or  Divisional member
- Changing Departments, If in the same Division then can be done by a Division member. If between 2 Division only Admin? 

What about movement within Divisions. Only doable by Admins?

thanks.

**Comment by mshappe** [comment]
The only things I think need to be editable (not add/drop) right now are Notes and Position-within-department (both restricted to Department Head and above). Changing departments can be drop/add; changing divisions can be drop/add.

**Comment by mshappe** [comment]
Had occasion to test this just yesterday for one of my departments, so we're good!
