### ISSUE TITLE
Portal: Concom List: Display information about divisional backups

### ISSUE THREAD

**Issue by mshappe** [CON-In-A-Box/CIAB-Portal#319]
Prereq: #318 

* The concom list, when displaying the header for a division, should include something like "Backed up by <backup-division>"
* The autodorgnut display of divisions should be ordered according to the backup pointer cycle.
* The autodorgnut should include an arrow that leads from a given division to the next one in backup order (see the official SRD-generated dorgnut for reference)

**Comment by AricStewart** [comment]
The patches are in.
