### ISSUE TITLE
Portal: Add prominent links to how to report issues

### ISSUE THREAD

**Issue by mshappe** [CON-In-A-Box/CIAB-Portal#328]
I'm about to set up a `portal-help@` email reflector. We should call this out and link to it everywhere there's an error or a possible issue (especially with login, etc).

**Comment by AricStewart** [comment]
<img width="1580" alt="Screen Shot 2019-11-01 at 7 09 14 AM" src="https://user-images.githubusercontent.com/1994679/68025287-6a3b6d80-fc7a-11e9-83ab-bf8cf379611b.png">

Thoughts on that as a bottom banner. Would be on all pages.

<img width="1578" alt="Screen Shot 2019-11-01 at 7 38 04 AM" src="https://user-images.githubusercontent.com/1994679/68025379-922ad100-fc7a-11e9-99ec-1d27cb4f9a7c.png">

**Comment by mshappe** [comment]
That's good, but it also should be a rote part of all error messages that
the user is supposed to see, especially the ones around signing in.
Something along the lines of "Please try again. If you're having persistent
issues, please <a>contact us</a>"....
--
Michael Scott Shappe
Director, Systems Division
Convergence Events, Inc

Help Amazon donate to CONvergence!
It's free and easy, Amazon does it all!
Always use smile.amazon.com <https://smile.amazon.com/ch/27-1445975>
instead of www!
Learn how <https://smile.amazon.com/ch/27-1445975> 1% of your purchases can
be donated!

**Comment by AricStewart** [comment]
Beginning work on this in Pull Request #330

**Comment by AricStewart** [comment]
The feedback link is in place. Maybe DeNae could itemize areas where more UI/messaging is desired in a more concrete way?

**Comment by AricStewart** [comment]
Reported as closed
