### ISSUE TITLE
Change a concom member's position in a department without removing/re-adding

### ISSUE THREAD

**Issue by mshappe** [CON-In-A-Box/CIAB-Portal#362]
As a department head or division director, I want to be able to change a concom member's position within a department without having to remove and re-add them.

Example: a certain Mr @AricStewart is now a Head of IT, but to change him from being a Specialist, I need to remove and re-add him right now. I should be able to just edit his position within the department.

**Comment by AricStewart** [comment]
Honestly the whole concom list could do with a good rewrite/redesign. Most of that code is from before me and even I generally try to avoid modifying it.

**Comment by mshappe** [comment]
Derp. Duplicates #307
