### ISSUE TITLE
Annual Meeting Attendance Report

### ISSUE THREAD

**Issue by tskeeley** [CON-In-A-Box/CIAB-Portal#379]
Need a CSV output of all official meetings in a cycle with who attended.  Output should be

Name, Email, <Meeting1>, <Meeting2>, ...

All meeting fields can be blank for false, non-blank for true (suggest "X")

Logic -
For voting reasons, we need to confirm that someone has been at a certain number of meetings.  The meetings they are at can also be used for validation purposes and review of attendance in non-voting reasons.

CVG Specific = Voting rights if at 2+ meetings.  But need raw data of those attending even just one meeting.  This will be paired with the 30+ hour volunteer list to qualify someone as a voter.

**Comment by AricStewart** [comment]
Where would you like something like this to hang?  Off of `ConCom List` or `Administer->Event & meetings` Should we have a new place?   If so what should it be called.

**Comment by mshappe** [comment]
Admin->Reports. I suspect we'll be needing more of those as time goes on. Might as well give 'em a section, now.

**Comment by tskeeley** [comment]
A LOT more, yes.  Admin reports is a good idea. If not, then Admin-Event/meeting

**Comment by tskeeley** [comment]
So happy.  When it hits production - it can be a Fix #379

**Comment by tskeeley** [comment]
Welps, that was dump.  Was looking for "Patch Pending" and accidentally removed priority.  oh well.

**Comment by AricStewart** [comment]
Fixes all in and it seems like it is working for me.
