### ISSUE TITLE
Registration report - Membership Sold Summary

### ISSUE THREAD

**Issue by dleverentz** [CON-In-A-Box/CIAB-Portal#399]
As a Registration Head/Sub-Head or Finance Head, I can view a report summarizing membership sold for the current event, so I can perform analysis and permanent records. 

**Acceptance Criteria**

- [ ] Provides the following information in this order for each type of membership:

- Badge Type
- Badge Cost
- Total Sold
- Total Revenue

- [ ]  Provides the ability to export the report as a CSV file

**Comment by AricStewart** [comment]
Development finished, code in master.

**Comment by dleverentz** [comment]
Reviewed in DEV - view report button did not work, download CSV button worked.
Report format looks good.
No data was pulled, so I can't validate that we are pulling correct data. @AricStewart should there have been data?

**Comment by AricStewart** [comment]
Try ciab.anergyst.org   credentials mailed to you.
