### ISSUE TITLE
Registration Report - Badge Pick Up Summary

### ISSUE THREAD

**Issue by dleverentz** [CON-In-A-Box/CIAB-Portal#400]
As a Registration Head/Sub-Head, I can view a report summarizing how many badges have been picked up, so I can monitor progress and staff appropriately. 

**Acceptance Criteria** 

- [ ] Provide the following information summarizing each badge type: 

- Badge Type
- Total Sold
- Total Picked Up

- [ ]  Provides the ability to export the report as a CSV file

**Comment by dleverentz** [comment]
This is effectively the warm body count - it needs to register the first time a badge is picked. 

Moving the browser visibility into a new story. - [ ]  Provides this information in the browser window

**Comment by AricStewart** [comment]
Development finished, code in master.

**Comment by dleverentz** [comment]
Reviewed in DEV - view report button did not work, download CSV button worked.
Report format looks good.
No data was pulled, so I can't validate that we are pulling correct data. @AricStewart should there have been data?

**Comment by AricStewart** [comment]
Try ciab.anergyst.org   credentials mailed to you.
