### ISSUE TITLE
BUG: notification of department changes doesn't actually include information

### ISSUE THREAD

**Issue by mshappe** [CON-In-A-Box/CIAB-Portal#414]
The e-mail notifications we get when changes are made to the concom list have blanks for who and what (this is a regression--I remember it working right after we introduced the feature).

**Comment by AricStewart** [comment]
What changes?
I presume Adding and removing members from the ConCom?
I am testing with my docker install and that appears to be working for me. 

`"Aric has added lorger CotRocrocpecdif to Activities."`

I dont want to 'play around' on production to see what is going on.

**Comment by mshappe** [comment]
Adds and deletions were not actually showing any text. You fixed it back in March and I **think** it's working now.
