### ISSUE TITLE
BUG: Issue adding notification

### ISSUE THREAD

**Issue by mshappe** [CON-In-A-Box/CIAB-Portal#419]
Hello,

I am trying to add an announcement requesting a new sub head but get an error message after the confirm update prompt, saying it is a PDOException.  I had this error around 7:43 PM CST on 3/25/2020.

The text I was trying to post is:

Hello, Book Swap is looking for a Sub-Head!  Responsibilities include getting CCd on all the emails and keeping track of what needs to be done for Con.  If you're interested in backing me up, please email bookswap@convergence-con.org with your interest!

I was sending this to ConCom only as selected in the dropdown, as book swap which had already been selected.

I was signed in under brandslick@gmail.com to do this.

Let me know if you need any other information.

**Comment by AricStewart** [comment]
Fix for this submitted. It was the ' character that was causing issues.
