### ISSUE TITLE
FEATURE: No way to edit/extend a cycle

### ISSUE THREAD

**Issue by mshappe** [CON-In-A-Box/CIAB-Portal#437]
Because the "cycle" this year is weird, we need to be able to do one of the following:

1. Extend the cycle that already exists beyond its current end date
2. Reassign a new cycle when the old one ends to an existing convention
3. Assign more than one cycle to a specific convention

This comes up because "CONvergence 2020" is now "CONvergence 2020-2021".

**Comment by AricStewart** [comment]
This should be resolved.

**Comment by mshappe** [comment]
It worked.
