### ISSUE TITLE
Associate meetings with CYCLES not with EVENTS

### ISSUE THREAD

**Issue by mshappe** [CON-In-A-Box/CIAB-Portal#439]
Right now, MEETINGS associate with EVENTS, which is a problem for 2020-2021. The organizational year (a CYCLE) matters for things like elector eligibility and is actually orthogonal to whether or not we had a convention!

**Comment by AricStewart** [comment]
You would be able to generate the desires reports now.

**Comment by AricStewart** [comment]
Good?  If so lets close this.
