### ISSUE TITLE
Updates to users profile do not propogate

### ISSUE THREAD

**Issue by tskeeley** [CON-In-A-Box/CIAB-Portal#586]
In portal, if you go to "profile" and update your info (specifically email for my test), the change is accepted, but does not show up else where (eg: the concom list)  Since the concom list in portal should be showing current info and is generated at time of load, this looks to be a bug with updates not getting to an account or a problem with the concom list generation.

Either way, if a user updates either profile info, it needs to update everywhere.  The concom mailing list also depends on this working correctly.

Affected steps:
Login -> profile -> change info -> click "update proflie" -> switch to "concom" -> find your name with old email in place.

**Comment by AricStewart** [comment]
Is it just email or is it other things.  Email is sort of a unique key used for account identification.  I will investigate but I am curious if it is specifically email that is the problem.

**Comment by AricStewart** [comment]
Just as a test I appear to have successfully updated my mailing address. so it may be an email issue.

**Comment by AricStewart** [comment]
Ok, I think this is because signin is still an unholy hybrid of neon and our data, I am investigating but I think it is because we are using the neon data as being correct for the e-mail address and not our local data. 
Changing email has always been a serious pain when connected to neon.

**Comment by tskeeley** [comment]
Makes sense.  But yes, it was email that was the problem.  People trying to
update to get latest updates.

I would rather not do this update manually, of course.  But if i have to, I
will.

-- Thomas Keeley

If a Smurf holds its breath for too long, what color does it turn??
Para. Jeff Dunham

**Comment by AricStewart** [comment]
I have not forgotten this, just been pulled in other directions.  I am looking and sure enough the current code all uses the backend API, whic does a lot of work to update the local database but does not propagate anything back to Neon.  However we are still using Neon for the loging credentials and then things get confused with email depending on if we are using the database source or Neon source.

Curse Neon!   I will try to find the cleanest and easiest way to fix this.

**Comment by AricStewart** [comment]
Pull request #587 address this and should solve it.

**Comment by AricStewart** [comment]
This should be resolved.
