### ISSUE TITLE
pecl/xdebug dependency issue in Docker

### ISSUE THREAD

**Issue by drraccoony** [CON-In-A-Box/CIAB-Portal#596]
Upon attempting to run the repo in docker, I get the following issue with a failure:
```
#0 27.52 WARNING: channel "pecl.php.net" has updated its protocols, use "pecl channel-update pecl.php.net" to update
#0 27.55 pecl/xdebug requires PHP (version >= 8.0.0, version <= 8.2.99), installed version is 7.2.7
#0 27.55 No valid packages found
#0 27.55 install failed
```

This can be resolved by changing xdebug to use 2.9.0 instead of latest.
```
pecl install xdebug-2.9.0
```

I can PR a fix to address this issue item later if nobody beats me to it.

**Comment by AricStewart** [comment]
Hello! Interesting.  How are you running docker?  I am not seeing this myself 

```
 $ docker-compose run --rm php pecl list
WARNING: Found orphan containers (ciab-signin_phpmyadmin_1) for this project. If you removed or renamed this service in your compose file, you can run this command with the --remove-orphans flag to clean it up.
Creating ciab-signin_php_run ... done
Installed packages, channel pecl.php.net:
=========================================
Package Version State
xdebug  3.0.4   stable
```
Are you proposing adding that the to the docker configuration. I am not a docker expert so I would love to see your PR and see how it works in my environment.  

Thanks!

**Comment by drraccoony** [comment]
You are likely rerunning an orphaned container which won't run into this issue. I am sure you'll hit the same issue if you spin up a brand new docker container without existing images on your system.

I ran docker to a T based on the `docker.md` file.

**Comment by drraccoony** [comment]
Created PR https://github.com/CON-In-A-Box/CIAB-Portal/pull/597

**Comment by AricStewart** [comment]
Thank you very much for the investigation and patch. All merged!
