### ISSUE TITLE
Registration Guest: Create new login account

### ISSUE THREAD

**Issue by seanbseanb** [CON-In-A-Box/CIAB-Portal#82]
As a Guest, I want to be able to create a new login (authentication credentials).  

If an account already exists associated with a given email address, this process should not create more than one account per email address, but instead prompt to reset the user’s password.

**Comment by seanbseanb** [comment]
I'd like this function to work using non-neon authentication in Con Year 2019.

**Comment by AricStewart** [comment]
This should now be functioning.

**Comment by mshappe** [comment]
Verified on master with a Neonless local install. NOTE: Member Registration search does NOT work to verify this because it's currently broken (at least for Neonless installs), but Admin->Database search worked.
