### ISSUE TITLE
Enter Hours Page: Volunteer Badge #, Email or Full Name Field: Wild Card Search

### ISSUE THREAD

**Issue by lmhern1** [CON-In-A-Box/CIAB-Portal#96]
Enhancement: CONSIDER adding a wild card search for a member. Adds the ability to search and find a volunteer without knowing exact information (such as correct spelling of first/last name, email address on file, etc)

**Comment by AricStewart** [comment]
This would be very hard at present. It could be down the road but I think there are more important things to focus on.  Do you mind if I send this down to a later version?

**Comment by lmhern1** [comment]
I do not mind and yes, that makes sense. Yes, there are more important things to focus on. 
Thanks!

**Comment by AricStewart** [comment]
Much of this is in place.
